name: Run tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Test ch1 with maven
        run: |
          root=$PWD
          cd ch1/maven
          mvn --batch-mode test

          cd "$root/ch1/gradle"
          ./gradlew check

          cd ch1/widget
          mvn --batch-mode test
